services:
  web-ui:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: kafka-demo/web-ui:latest
    container_name: kafka-web-ui
    depends_on:
      - order-service
      - notification-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
    ports:
      - "8080:8080"

  order-service:
    build:
      context: services/order-service
      dockerfile: src/main/docker/Dockerfile.jvm
    image: kafka-demo/order-service:latest
    container_name: order-service
    depends_on:
      - kafka-broker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
    ports:
      - "8081:8081"

  notification-service:
    build:
      context: services/notification-service
      dockerfile: src/main/docker/Dockerfile.jvm
    image: kafka-demo/notification-service:latest
    container_name: notification-service
    depends_on:
      - kafka-broker
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka-broker:29092
    ports:
      - "8082:8082"

  kafka-broker:
    image: apache/kafka:latest
    container_name: kafka-broker
    hostname: kafka-broker
    ports:
      - "9092:9092"
      - "39092:39092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092,HOST://0.0.0.0:39092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-broker:29092,EXTERNAL://kafka-broker:9092,HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "kafka-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-broker:29092
      KAFKA_CLUSTERS_0_READONLY: "false"
    depends_on:
      - kafka-broker
